// GERADO POR scripts/build-tabelas.ts — NÃO EDITE À MÃO.
// Fonte: TABELAS.xlsx (raiz do projeto, fora do git). Para regerar:
//   npm run data:tabelas
//
// Classificações orçamentárias oficiais. Os helpers que as consultam — nomeFuncao,
// nomeSubfuncao, nomeFonte e companhia — moram em referencias.ts.

/** Subfunções — Portaria MOG nº 42/1999. Código de três dígitos. */
export const SUBFUNCOES: Record<string, string> = {
  "121": "Planejamento e Orçamento",
  "122": "Administração Geral",
  "123": "Administração Financeira",
  "124": "Controle Interno",
  "125": "Normatização e Fiscalização",
  "126": "Tecnologia da Informação",
  "127": "Ordenamento Territorial",
  "128": "Formação de Recursos Humanos",
  "129": "Administração de Receitas",
  "130": "Administração de Concessões",
  "131": "Comunicação Social",
  "151": "Defesa Aérea",
  "152": "Defesa Naval",
  "153": "Defesa Terrestre",
  "181": "Policiamento",
  "182": "Defesa Civil",
  "183": "Informação e Inteligência",
  "211": "Relações Diplomáticas",
  "212": "Cooperação Internacional",
  "241": "Assistência à Pessoa Idosa",
  "242": "Assistência à Pessoa com Deficiência",
  "243": "Assistência à Criança e ao Adolescente",
  "244": "Assistência Comunitária",
  "245": "Serviços Socioassistenciais",
  "246": "Segurança de Renda",
  "271": "Previdência Básica",
  "272": "Previdência do Regime Estatutário",
  "273": "Previdência Complementar",
  "274": "Previdência Especial",
  "301": "Atenção Básica",
  "302": "Assistência Hospitalar e Ambulatorial",
  "303": "Suporte Profilático e Terapêutico",
  "304": "Vigilância Sanitária",
  "305": "Vigilância Epidemiológica",
  "306": "Alimentação e Nutrição",
  "331": "Proteção e Benefícios ao Trabalhador",
  "332": "Relações de Trabalho",
  "333": "Empregabilidade",
  "334": "Fomento ao Trabalho",
  "361": "Ensino Fundamental",
  "362": "Ensino Médio",
  "363": "Ensino Profissional",
  "364": "Ensino Superior",
  "365": "Educação Infantil",
  "366": "Educação de Jovens e Adultos",
  "367": "Educação Especial",
  "368": "Educação Básica",
  "391": "Patrimônio Histórico, Artístico e Arqueológico",
  "392": "Difusão Cultural",
  "421": "Custódia e Reintegração Social",
  "422": "Direitos Individuais, Coletivos e Difusos",
  "423": "Assistência aos Povos Indígenas",
  "451": "Infra-Estrutura Urbana",
  "452": "Serviços Urbanos",
  "453": "Transportes Coletivos Urbanos",
  "481": "Habitação Rural",
  "482": "Habitação Urbana",
  "511": "Saneamento Básico Rural",
  "512": "Saneamento Básico Urbano",
  "541": "Preservação e Conservação Ambiental",
  "542": "Controle Ambiental",
  "543": "Recuperação de Áreas Degradadas",
  "544": "Recursos Hídricos",
  "545": "Meteorologia",
  "571": "Desenvolvimento Científico",
  "572": "Desenvolvimento Tecnológico e Engenharia",
  "573": "Difusão do Conhecimento Científico e Tecnológico",
  "601": "Promoção da Produção Vegetal",
  "602": "Promoção da Produção Animal",
  "603": "Defesa Sanitária Vegetal",
  "604": "Defesa Sanitária Animal",
  "605": "Abastecimento",
  "606": "Extensão Rural",
  "607": "Irrigação",
  "608": "Promoção da Produção Agropecuária",
  "609": "Defesa Agropecuária",
  "631": "Reforma Agrária",
  "632": "Colonização",
  "661": "Promoção Industrial",
  "662": "Produção Industrial",
  "663": "Mineração",
  "664": "Propriedade Industrial",
  "665": "Normalização e Qualidade",
  "691": "Promoção Comercial",
  "692": "Comercialização",
  "693": "Comércio Exterior",
  "694": "Serviços Financeiros",
  "695": "Turismo",
  "721": "Comunicações Postais",
  "722": "Telecomunicações",
  "751": "Conservação de Energia",
  "752": "Energia Elétrica",
  "753": "Combustíveis Minerais",
  "754": "Biocombustíveis",
  "781": "Transporte Aéreo",
  "782": "Transporte Rodoviário",
  "783": "Transporte Ferroviário",
  "784": "Transporte Aquaviário",
  "785": "Transportes Especiais",
  "811": "Desporto de Rendimento",
  "812": "Desporto Comunitário",
  "813": "Lazer",
  "841": "Refinanciamento da Dívida Interna",
  "842": "Refinanciamento da Dívida Externa",
  "843": "Serviço da Dívida Interna",
  "844": "Serviço da Dívida Externa",
  "845": "Outras Transferências",
  "846": "Outros Encargos Especiais",
  "847": "Transferências para a Educação Básica",
  "031": "Ação Legislativa",
  "032": "Controle Externo",
  "061": "Ação Judiciária",
  "062": "Defesa do Interesse Público no Processo Judiciário",
  "091": "Defesa da Ordem Jurídica",
  "092": "Representação Judicial e Extrajudicial",
};

/** Programas temáticos do PPA. Código de quatro dígitos. */
export const PROGRAMAS_TEMATICOS: Record<string, string> = {
  "1431": "SEGURANÇA PÚBLICA E PROTEÇÃO A VIDA",
  "1432": "GESTÃO INTEGRADA E DEMOCRATIZADA DA CULTURA DA CULTURA",
  "1433": "VALORIZAÇÃO, CAPACITAÇÃO E CUIDADO DOS SERVIDORES PÚBLICOSDO DOS SERVIDORES PÚBLICOS",
  "1434": "REFAZENDO E CRIANDO NOVOS CAMINHOS NA SOCIOEDUCAÇÃO.CAMINHOS NA SOCIOEDUCAÇÃO.",
  "1435": "CONSTRUÇÃO, REFORMA E AMPLIAÇÃO DOS PRÉDIOS PÚBLICOS ESTADUAIS.DOS PRÉDIOS PÚBLICOS ESTADUAIS.",
  "1436": "POVOS INDÍGENAS EM AÇÃO PELO CLIMA: PRESERVANDO CULTURAS, SALVAGUARDANDO O FUTURO.",
  "1437": "DEFESA CIVIL ESTADUAL.",
  "1438": "PROFISSIONALIZA ACRE.",
  "1439": "PROTEÇÃO E DEFESA DOS DIREITOS DO CONSUMIDOR.",
  "1440": "\"MINHA TERRA DE PAPEL PASSADO\"",
  "1441": "REGULAÇÃO, CONTROLE E FISCALIZAÇÃO DOS SERVIÇOS PÚBLICOS DELEGADOS.ÃO DOS SERVIÇOS PÚBLICOS DELEGAD",
  "1442": "DIFUSÃO E COMUNICAÇÃO PÚBLICA.",
  "1443": "INFRAESTRUTURA E MOBILIDADE URBANA.NA.",
  "1444": "A CASA É SUA.",
  "1445": "DEFESA E INSPEÇÃO AGROPECUÁRIA.",
  "1446": "DESENVOLVIMENTO DA PRODUÇÃO FAMILIAR, BIOECONOMIA E AGRONEGÓCIO.LIAR, BIOECONOMIA E AGRONEGÓCIO.",
  "1447": "DESENVOLVIMENTO DOS NEGÓCIOS ACREANOSEANOS",
  "1448": "SEGURANÇA NO TRÂNSITO.",
  "1449": "REINTEGRAÇÃO SOCIAL NO SISTEMA PRISIONAL: CONSTRUINDO DIGNIDADES.RISIONAL: CONSTRUINDO DIGNIDADES",
  "1450": "EDUCAÇÃO BÁSICA DE QUALIDADE.",
  "1451": "Esporte e Juventude.",
  "1452": "DIREITOS HUMANOS E SEGURANÇA ESCOLAR.OLAR.",
  "1453": "SANEIA ACRE.",
  "1454": "INTEGRAÇÃO DA COMUNIDADE E SEGURANÇA PÚBLICA.ANÇA PÚBLICA.",
  "1455": "MEU BEM, MINHA HISTÓRIA.",
  "1456": "ADVOCACIA PÚBLICA, DIÁLOGO E CIDADANIA.ADANIA.",
  "1457": "FORTALECIMENTO DA CIÊNCIA, TECNOLOGIA E ECOSSISTEMA INOVADOR.LOGIA E ECOSSISTEMA INOVADOR.",
  "1458": "GESTÃO, TRANSPARÊNCIA E SERVIÇOS PÚBLICOS. PÚBLICOS.",
  "1459": "REGULARIZAÇÃO, CONTROLE E MONITORAMENTO AMBIENTAL.RAMENTO AMBIENTAL.",
  "1460": "ECOSSISTEMA DE INOVAÇÃO AMBIENTAL E ADAPTAÇÃO CLIMÁTICA.L E ADAPTAÇÃO CLIMÁTICA.",
  "1461": "MULHER, TRANSVERSALIDADE E FORÇA..",
  "1462": "ACRE EMPREENDEDOR.",
  "1463": "VIVENCIA ACRE.",
  "1464": "DESENVOLVIMENTO REGIONAL SUSTETÁNVELNVEL",
  "1465": "SAÚDE, UM NOVO OLHAR.",
  "1466": "MODERNIZAÇÃO DA GESTÃO TRIBUTÁRIA, FISCAL, FINANCEIRA E CONTÁBIL.A, FISCAL, FINANCEIRA E CONTÁBIL",
  "1467": "GOVERNANÇA E GESTÃO DA ADMINISTRAÇÃO TRIBUTÁRIA.AÇÃO TRIBUTÁRIA.",
  "1468": "GESTÃO COM FOCO NOS SERVIDORES.",
  "1469": "CONSOLIDA SUAS ACRE.",
  "1470": "CIDADANIA E DIREITOS HUMANOS.",
  "1471": "CONSOLIDA SISAN ACRE.",
  "1472": "JUNTOS PELO ACRE",
  "1473": "FORTALECIMENTO DA QUALIDADE E AGILIDADE DO CONTROLE EXTERNO.ILIDADE DO CONTROLE EXTERNO.",
  "1474": "GESTÃO ESTRATÉGICA E RESOLUTIVA.",
  "1475": "PLANEJAMENTO E GOVERNANÇA PARA RESULTADOESULTADO",
  "2286": "GESTÃO INSTITUCIONAL EXECUTIVO: ADMINISTRATIVO E OPERACIONAL.ADMINISTRATIVO E OPERACIONAL.",
  "2287": "GESTÃO INSTITUCIONAL EXECUTIVO: FUNDO PREVIDENCIÁRIOFUNDO PREVIDENCIÁRIO",
  "2288": "GESTÃO INSTITUCIONAL EXECUTIVO: CONTROLE E SERVIÇO DA DÍVIDA.CONTROLE E SERVIÇO DA DÍVIDA.",
  "2289": "GESTÃO INSTITUCIONAL EXECUTIVO: FOLHA DE PAGAMENTO.FOLHA DE PAGAMENTO.",
  "2290": "GESTÃO INSTITUCIONAL LEGISLATIVO (ASSEMBLÉIA LEGISLATIVA). (ASSEMBLÉIA LEGISLATIVA).",
  "2291": "GESTÃO INSTITUCIONAL LEGISLATIVO (TRIBUNAL DE CONTAS). (TRIBUNAL DE CONTAS).",
  "2292": "GESTÃO INSTITUCIONAL LEGISLATIVO (EMENDAS PARLAMENTARES). (EMENDAS PARLAMENTARES).",
  "2293": "GESTÃO INSTITUCIONAL JUDICIÁRIO.",
  "2294": "GESTÃO INSTITUCIONAL MINISTÉRIO PÚBLICO ESTADUAL.PÚBLICO ESTADUAL.",
  "2295": "GESTÃO INSTITUCIONAL DEFENSORIA PÚBLICA ESTADUAL.PÚBLICA ESTADUAL.",
  "2296": "GESTÃO E MANUTENÇÃO DAS ATIVIDADES DE CONTROLE EXTERNO (TRIBUNAL DE CONTAS).ES DE CONTROLE EXTERNO (TRIBUNAL",
  "9999": "RESERVA DE CONTINGÊNCIA.",
};

/**
 * Programa do PPA → eixo do PPA.
 *
 * **Este eixo NÃO é o eixo do OSG.** O eixo do OSG são os seis do art. 4º da Lei
 * estadual nº 4.168/2023, em `EIXOS` (referencias.ts), que dão as cores e os
 * gráficos do painel inteiro. Este aqui é o eixo temático do PPA estadual, outra
 * classificação com o mesmo nome. Os dois só aparecem lado a lado na planilha de
 * exportação, com rótulos que os distinguem; na tela, "eixo" quer dizer o do OSG.
 */
export const EIXO_PPA_POR_PROGRAMA: Record<string, string> = {
  "1431": "DESENVOLVIMENTO SOCIAL E SEGURANÇA PÚBLICA",
  "1432": "CULTURA E TURISMO",
  "1433": "GESTÃO INSTITUCIONAL E GOVERNANÇA",
  "1434": "DESENVOLVIMENTO SOCIAL E SEGURANÇA PÚBLICA",
  "1435": "INFRAESTRUTURA",
  "1436": "PRODUÇÃO, MEIO AMBIENTE E POVOS INDÍGENAS",
  "1437": "DESENVOLVIMENTO SOCIAL E SEGURANÇA PÚBLICA",
  "1438": "DESENVOLVIMENTO SOCIAL E SEGURANÇA PÚBLICA",
  "1439": "DESENVOLVIMENTO SOCIAL E SEGURANÇA PÚBLICA",
  "1440": "INFRAESTRUTURA",
  "1441": "INFRAESTRUTURA",
  "1442": "GESTÃO INSTITUCIONAL E GOVERNANÇA",
  "1443": "INFRAESTRUTURA",
  "1444": "INFRAESTRUTURA",
  "1445": "PRODUÇÃO, MEIO AMBIENTE E POVOS INDÍGENAS",
  "1446": "PRODUÇÃO, MEIO AMBIENTE E POVOS INDÍGENAS",
  "1447": "AMBIENTE DE NEGÓCIOS, EMPREENDEDORISMO E INOVAÇÃO",
  "1448": "DESENVOLVIMENTO SOCIAL E SEGURANÇA PÚBLICA",
  "1449": "DESENVOLVIMENTO SOCIAL E SEGURANÇA PÚBLICA",
  "1450": "DESENVOLVIMENTO SOCIAL E SEGURANÇA PÚBLICA",
  "1451": "DESENVOLVIMENTO SOCIAL E SEGURANÇA PÚBLICA",
  "1452": "DESENVOLVIMENTO SOCIAL E SEGURANÇA PÚBLICA",
  "1453": "INFRAESTRUTURA",
  "1454": "DESENVOLVIMENTO SOCIAL E SEGURANÇA PÚBLICA",
  "1455": "GESTÃO INSTITUCIONAL E GOVERNANÇA",
  "1456": "GESTÃO INSTITUCIONAL E GOVERNANÇA",
  "1457": "AMBIENTE DE NEGÓCIOS, EMPREENDEDORISMO E INOVAÇÃO",
  "1458": "GESTÃO INSTITUCIONAL E GOVERNANÇA",
  "1459": "PRODUÇÃO, MEIO AMBIENTE E POVOS INDÍGENAS",
  "1460": "PRODUÇÃO, MEIO AMBIENTE E POVOS INDÍGENAS",
  "1461": "DESENVOLVIMENTO SOCIAL E SEGURANÇA PÚBLICA",
  "1462": "AMBIENTE DE NEGÓCIOS, EMPREENDEDORISMO E INOVAÇÃO",
  "1463": "CULTURA E TURISMO",
  "1464": "GESTÃO INSTITUCIONAL E GOVERNANÇA",
  "1465": "DESENVOLVIMENTO SOCIAL E SEGURANÇA PÚBLICA",
  "1466": "GESTÃO INSTITUCIONAL E GOVERNANÇA",
  "1467": "GESTÃO INSTITUCIONAL E GOVERNANÇA",
  "1468": "GESTÃO INSTITUCIONAL E GOVERNANÇA",
  "1469": "DESENVOLVIMENTO SOCIAL E SEGURANÇA PÚBLICA",
  "1470": "DESENVOLVIMENTO SOCIAL E SEGURANÇA PÚBLICA",
  "1471": "DESENVOLVIMENTO SOCIAL E SEGURANÇA PÚBLICA",
  "1472": "DESENVOLVIMENTO SOCIAL E SEGURANÇA PÚBLICA",
  "1473": "DEMAIS PODERES",
  "1474": "DEMAIS PODERES",
  "1475": "GESTÃO INSTITUCIONAL E GOVERNANÇA",
  "2286": "GESTÃO",
  "2287": "GESTÃO",
  "2288": "GESTÃO",
  "2289": "GESTÃO",
  "2290": "DEMAIS PODERES",
  "2291": "DEMAIS PODERES",
  "2292": "GESTÃO",
  "2293": "DEMAIS PODERES",
  "2294": "DEMAIS PODERES",
  "2295": "DEMAIS PODERES",
  "2296": "DEMAIS PODERES",
  "9999": "GESTÃO",
};

/** Categoria econômica da despesa — primeiro dígito da conta de despesa. */
export const CATEGORIAS_ECONOMICAS: Record<string, string> = {
  "3": "Despesas Correntes",
  "4": "Despesas de Capital",
};

/** Grupo de natureza da despesa — segundo dígito da conta de despesa. */
export const GRUPOS_NATUREZA: Record<string, string> = {
  "1": "Pessoal e Encargos Sociais",
  "2": "Juros e Encargos da Dívida",
  "3": "Outras Despesas Correntes",
  "4": "Investimentos",
  "5": "Inversões Financeiras",
  "6": "Amortização da Dívida",
  "9": "Reserva de Contigência",
};

/** Modalidade de aplicação — terceiro e quarto dígitos da conta de despesa. */
export const MODALIDADES_APLICACAO: Record<string, string> = {
  "20": "Transferências à União",
  "22": "Execução Orçamentária Delegada à União",
  "24": "da Lei Complementar nº 141, de 2012",
  "25": "da Lei Complementar nº 141, de 2012",
  "30": "Transferências a Estados e ao Distrito Federal",
  "31": "Transferências a Estados e ao Distrito Federal - Fundo a Fundo",
  "32": "Execução Orçamentária Delegada a Estados e ao Distrito Federal",
  "35": "Transferências Fundo a Fundo aos Estados e ao Distrito Federal à conta de recursos de que tratam os §§ 1º e 2º do art. 24 da Lei Complementar nº 141, de 2012",
  "36": "Transferências Fundo a Fundo aos Estados e ao Distrito Federal à conta de recursos de que trata o art. 25 da Lei Complementar nº 141, de 2012",
  "40": "Transferências a Municípios",
  "41": "Transferências a Municípios - Fundo a Fundo",
  "42": "Execução Orçamentária Delegada a Municípios",
  "45": "Transferências Fundo a Fundo aos Municípios à conta de recursos de que tratam os §§ 1º e 2º do art. 24 da Lei Complementar nº 141, de 2012",
  "46": "Transferências Fundo a Fundo aos Municípios à conta de recursos de que trata o art.",
  "50": "Transferências a Instituições Privadas sem Fins Lucrativos",
  "60": "Transferências a Instituições Privadas com Fins Lucrativos",
  "67": "Execução de Contrato de Parceria Público-Privada – PPP",
  "70": "Transferências a Instituições Multigovernamentais",
  "71": "Transferências a Consórcios Públicos mediante contrato de rateio",
  "72": "Execução Orçamentária Delegada a Consórcios Públicos",
  "73": "Transferências a Consórcios Públicos mediante contrato de rateio à conta de recursos de que tratam os §§ 1º e 2º do art. 24 da Lei Complementar nº 141, de 2012",
  "74": "Transferências a Consórcios Públicos mediante contrato de rateio à conta de recursos de que trata o art. 25 da Lei Complementar nº 141, de 2012",
  "75": "Transferências a Instituições Multigovernamentais à conta de recursos de que tratam os §§ 1º e 2º do art.",
  "76": "Transferências a Instituições Multigovernamentais à conta de recursos de que trata o art. 25 da Lei Complementar nº 141, de 2012",
  "80": "Transferências ao Exterior",
  "90": "Aplicações Diretas",
  "91": "Aplicação Direta Decorrente de Operação entre Órgãos, Fundos e Entidades Integrantes dos Orçamentos Fiscal e da Seguridade Social",
  "92": "Aplicação Direta de Recursos Recebidos de Outros Entes da Federação Decorrentes de Delegação ou Descentralização",
  "93": "Aplicação Direta Decorrente de Operação de Órgãos, Fundos e Entidades Integrantes dos Orçamentos Fiscal e da Seguridade Social com Consórcio Público do qual o Ente Participe",
  "94": "Aplicação Direta Decorrente de Operação de Órgãos, Fundos e Entidades Integrantes dos Orçamentos Fiscal e da Seguridade Social com Consórcio Público do qual o Ente Não Participe",
  "95": "Aplicação Direta à conta de recursos de que tratam os §§ 1º e 2º do art. 24 da Lei Complementar nº 141, de 2012",
  "96": "Aplicação Direta à conta de recursos de que trata o art. 25 da Lei Complementar nº 141, de 2012",
  "99": "A definir",
};

/** Elemento de despesa — quinto e sexto dígitos da conta de despesa. */
export const ELEMENTOS_DESPESA: Record<string, string> = {
  "10": "Seguro Desemprego e Abono Salarial",
  "11": "Vencimentos e Vantagens Fixas – Pessoal Civil",
  "12": "Vencimentos e Vantagens Fixas – Pessoal Militar",
  "13": "Obrigações Patronais",
  "14": "Diárias – Civil",
  "15": "Diárias – Militar",
  "16": "Outras Despesas Variáveis – Pessoal Civil",
  "17": "Outras Despesas Variáveis – Pessoal Militar",
  "18": "Auxílio Financeiro a Estudantes",
  "19": "Auxílio-Fardamento",
  "20": "Auxílio Financeiro a Pesquisadores",
  "21": "Juros sobre a Dívida por Contrato",
  "22": "Outros Encargos sobre a Dívida por Contrato",
  "23": "Juros, Deságios e Descontos da Dívida Mobiliária",
  "24": "Outros Encargos sobre a Dívida Mobiliária",
  "25": "Encargos sobre Operações de Crédito por Antecipação da Receita",
  "26": "Obrigações decorrentes de Política Monetária",
  "27": "Encargos pela Honra de Avais, Garantias, Seguros e Similares",
  "28": "Remuneração de Cotas de Fundos Autárquicos",
  "29": "Distribuição de Resultado de Empresas Estatais Dependentes",
  "30": "Material de Consumo",
  "31": "Premiações Culturais, Artísticas, Científicas, Desportivas e Outras",
  "32": "Material, Bem ou Serviço para Distribuição Gratuita",
  "33": "Passagens e Despesas com Locomoção",
  "34": "Outras Despesas de Pessoal decorrentes de Contratos de Terceirização",
  "35": "Serviços de Consultoria",
  "36": "Outros Serviços de Terceiros – Pessoa Física",
  "37": "Locação de Mão-de-Obra",
  "38": "Arrendamento Mercantil",
  "39": "Outros Serviços de Terceiros – Pessoa Jurídica",
  "40": "Serviços de Tecnologia da Informação e Comunicação - Pessoa Jurídica",
  "41": "Contribuições",
  "42": "Auxílios",
  "43": "Subvenções Sociais",
  "45": "Subvenções Econômicas",
  "46": "Auxílio-Alimentação",
  "47": "Obrigações Tributárias e Contributivas",
  "48": "Outros Auxílios Financeiros a Pessoas Físicas",
  "49": "Auxílio-Transporte",
  "51": "Obras e Instalações",
  "52": "Equipamentos e Material Permanente",
  "53": "Aposentadorias do RGPS – Área Rural",
  "54": "Aposentadorias do RGPS – Área Urbana",
  "55": "Pensões do RGPS – Área Rural",
  "56": "Pensões do RGPS – Área Urbana",
  "57": "Outros Benefícios do RGPS – Área Rural",
  "58": "Outros Benefícios do RGPS – Área Urbana",
  "59": "Pensões Especiais",
  "61": "Aquisição de Imóveis",
  "62": "Aquisição de Produtos para Revenda",
  "63": "Aquisição de Títulos de Crédito",
  "64": "Aquisição de Títulos Representativos de Capital já Integralizado",
  "65": "Constituição ou Aumento de Capital de Empresas",
  "66": "Concessão de Empréstimos e Financiamentos",
  "67": "Depósitos Compulsórios",
  "70": "Rateio pela participação em Consórcio Público",
  "71": "Principal da Dívida Contratual Resgatado",
  "72": "Principal da Dívida Mobiliária Resgatado",
  "73": "Correção Monetária ou Cambial da Dívida Contratual Resgatada",
  "74": "Correção Monetária ou Cambial da Dívida Mobiliária Resgatada",
  "75": "Correção Monetária da Dívida de Operações de Crédito por Antecipação de Receita",
  "76": "Principal Corrigido da Dívida Mobiliária Refinanciado",
  "77": "Principal Corrigido da Dívida Contratual Refinanciado",
  "81": "Distribuição Constitucional ou Legal de Receitas",
  "82": "Aporte de Recursos pelo Parceiro Público em Favor do Parceiro Privado Decorrente de Contrato de Parceria Público-Privada - PPP",
  "83": "Despesas Decorrentes de Contrato de Parceria Público-Privada - PPP, exceto Subvenções Econômicas, Aporte e Fundo Garantidor",
  "84": "Despesas Decorrentes da Participação em Fundos, Organismos, ou Entidades Assemelhadas, Nacionais e Internacionais",
  "85": "Contrato de Gestão",
  "86": "Compensações a Regimes de Previdência",
  "91": "Sentenças Judiciais",
  "92": "Despesas de Exercícios Anteriores",
  "93": "Indenizações e Restituições",
  "94": "Indenizações e Restituições Trabalhistas",
  "95": "Indenização pela Execução de Trabalhos de Campo",
  "96": "Ressarcimento de Despesas de Pessoal Requisitado",
  "97": "Aporte para Cobertura do Déficit Atuarial do RPPS",
  "98": "Despesas do Orçamento de Investimento",
  "99": "A Classificar",
  "01": "Aposentadorias, Reserva Remunerada e Reformas",
  "03": "Pensões",
  "04": "Contratação por Tempo Determinado",
  "06": "Benefício Mensal ao Deficiente e ao Idoso",
  "07": "Contribuição a Entidades Fechadas de Previdência",
  "08": "Outros Benefícios Assistenciais do Servidor e do Militar",
};

/**
 * Fontes de recurso, no padrão de oito dígitos da Portaria STN nº 710/2021.
 *
 * O QDD traz códigos que não estão aqui — inclusive alguns de sete dígitos, que
 * parecem truncados na origem. Por isso `nomeFonte` devolve o código nu quando
 * não encontra, e nada neste projeto normaliza o comprimento do código: mexer no
 * comprimento transformaria um código malformado em outro código válido.
 */
export const FONTES: Record<string, string> = {
  "15000100": "RECURSOS PRÓPRIOS DO TESOURO",
  "15001001": "RECURSOS DESTINADOS À MAN. E DES. DO ENSINO (25%)",
  "15001002": "RECURSOS DEST. AO DES. DAS AÇÕES DE SAÚDE (12%)",
  "15010100": "OUTRAS RESTITUIÇÕES AOS PODERES",
  "15010600": "RECURSOS ORDINÁRIOS DESVINCULADOS - DRE",
  "15010700": "RECURSOS PRÓPRIOS DA ADM. INDIRETA – REC. NÃO VINCULADOS",
  "15010701": "RECURSOS DO CIRA - NÃO VINCULADOS.",
  "15400300": "TRANSF. DO FUNDEB - IMPOSTOS E TRANSF. DE IMPOSTOS",
  "15401070": "IDENT. DO PERC. APLIC. NA REMUN. PROF. DA EDUCAÇÃO BÁSICA",
  "15420300": "TRANSF. DO FUNDEB - COMPLEMENTAÇÃO DA UNIÃO - VAAT",
  "15430300": "TRANSF. DO FUNDEB - COMPLEMENTAÇÃO DA UNIÃO - VAAR",
  "15460000": "TRANSFERÊNCIAS DO FUNDEB - COMPLEMENTAÇÃO DA UNIÃO - ETI",
  "15500102": "TRANSFERÊNCIAS DO SALÁRIO-EDUCAÇÃO",
  "15520200": "TRANSF. DE RECURSOS DO FNDE REFERENTES AO PNAE",
  "15530200": "TRANSF. DE RECURSOS DO FNDE REFERENTES AO PNATE",
  "15700200": "TRANSF. DO GOV. FEDERAL-CONVÊNIOS/REPASSES VINC. A EDUCAÇÃO",
  "15703110": "EMENDAS PARLAMENTARES INDIVIDUAIS (EDUCAÇÃO)",
  "15703120": "EMENDAS PARLAMENTARES DE BANCADA (EDUCAÇÃO)",
  "15703130": "EMENDAS PARLAMENTARES DE COMISSÃO (EDUCAÇÃO)",
  "15730100": "ROYALTIES DO PETRÓLEO E GÁS NATURAL VINC. À EDUCAÇÃO (75%)",
  "15750200": "OUTRAS TRANSF. DE CONVÊNIOS VINCULADOS À EDUCAÇÃO",
  "16000400": "SUS - MANUTENÇÃO",
  "16003110": "EMENDAS PARLAMENTARES INDIVIDUAIS",
  "16003120": "EMENDAS PARLAMENTARES DE BANCADA",
  "16003130": "EMENDAS PARLAMENTARES DE COMISSÃO",
  "16003140": "EMENDAS PARLAMENTARES DE RELATOR.",
  "16010400": "SUS - INVESTIMENTOS",
  "16013110": "EMENDAS PARLAMENTARES INDIVIDUAIS",
  "16013120": "EMENDAS PARLAMENTARES DE BANCADA",
  "16013130": "EMENDAS PARLAMENTARES DE COMISSÃO.",
  "16013140": "EMENDAS PARLAMENTARES DE RELATOR.",
  "16020400": "REC. PARA AÇÕES E SERV DE SAÚDE - BLOCO MANUTENÇÃO COVID",
  "16030400": "REC. DAS AÇÕES E SERV DE SAÚDE - BLOCO INVESTIMENTO COVID",
  "16050400": "COMP. PAGAMENTO DO PISO SALARIAL DA ENFERMAGEM",
  "16310200": "TRANSFERÊNCIAS DO GOVERNO FEDERAL REFERENTES A CONVÊNIOS E INSTRUMENTOS CONGÊNERES VINCULADOS À SAÚD",
  "16313110": "EMENDAS PARLAMENTARES INDIVIDUAIS (SAÚDE)",
  "16313120": "EMENDAS PARLAMENTARES DE BANCADA (SAÚDE)",
  "16313130": "EMENDAS PARLAMENTARES DE COMISSÃO.(SAÚDE)",
  "16313140": "EMENDAS PARLAMENTARES DE RELATOR (SAÚDE)",
  "16350100": "ROYALTIES DO PETRÓLEO E GÁS NATURAL VINC À SAÚDE (25%)",
  "16360200": "OUTRAS TRANSF DE CONV/INSTRUMENTOS CONGÊNERES VINC À SAÚDE",
  "16600200": "TRANSF DE RECURSOS DO FUNDO NACIONAL DE ASSIST SOCIAL - FNAS",
  "16603110": "EMENDAS PARLAMENTARES INDIVIDUAIS",
  "16603120": "EMENDAS PARLAMENTARES DE BANCADA (FNS)",
  "16650200": "Transferências de Convênios e outros Repasses vinculados à Assistência Social",
  "16653110": "EMENDAS PARLAMENTARES INDIVIDUAIS (ASSISTÊNCIA SOCIAL)",
  "16653120": "EMENDAS PARLAMENTARES DE BANCADA (ASSISTÊNCIA SOCIAL)",
  "16653130": "EMENDA DE COMISSÃO (ASSISTÊNCIA SOCIAL)",
  "17000200": "OUTRAS TRANSFERÊNCIAS DE CONVÊNIOS OU REPASSES DA UNIÃO",
  "17000221": "TRANSFERÊNCIA DA UNIÃO - DEFESA CIVIL",
  "17003110": "EMENDAS PARLAMENTARES INDIVIDUAIS",
  "17003120": "EMENDAS PARLAMENTARES DE BANCADA",
  "17003130": "EMENDAS PARLAMENTARES DE COMISSÃO",
  "17003140": "EMENDAS PARLAMENTARES DE RELATOR.",
  "17010200": "OUTRAS TRANSFERÊNCIAS DE CONVÊNIOS OU INSTRUMENTOS CONGÊNERES DOS ESTADOS",
  "17020200": "OUTRAS TRANSFERÊNCIAS DE CONVÊNIOS OU INSTRUMENTOS CONGÊNERES DOS MUNICÍPIOS",
  "17030200": "CONTRIBUIÇÃO FINANCEIRA NÃO REEMBOLSÁVEL",
  "17030202": "FUNDO AMAZÔNIA",
  "17030203": "PROCAPE/FOCEM",
  "17040704": "TRANSF DA UNIÃO REF A ROYALTIES DO PETRÓLEO E GÁS NATURAL",
  "17060201": "TRANSFERÊNCIA ESPECIAL DA UNIÃO",
  "17063110": "TRANSFERÊNCIA ESPECIAL DA UNIÃO.",
  "17070900": "RECURSOS DA LC 173/2020",
  "17120700": "TRANSFERÊNCIAS REC FUNDO PENITENCIÁRIO - FUNPEN",
  "17130700": "TRANSF FUNDO A FUNDO DE RECURSOS DO FSP",
  "17140200": "TRANSF FUNDO A FUNDO-RECURSOS DO FAT",
  "17150013": "TRANSF DEST AO SETOR CULTURAL-LC Nº195/2022-ART.5º AUDIOVIS",
  "17160013": "TRANSF AO SETOR CULTURAL-LC Nº195/2022-ART.8º-DEMAIS SETORES",
  "17190013": "TRANSF POLÍTICA NAC DE FOMENTO À CULTURA-LEI Nº 14.399/2022",
  "17500101": "CIDE - COMBUSTÍVEIS",
  "17520700": "RECURSOS PROVENIENTES DA ARRECADAÇÃO DE MULTAS DE TRÂNSITO",
  "17530700": "RECURSOS PROVENIENTES DE TAXAS E CONTR E PREÇOS PÚBLICOS",
  "17540100": "RECURSOS DE DEPÓSITOS JUDICIAIS ¿ LIDES DAS QUAIS O ENTE FAZ PARTE.",
  "17540500": "OPERAÇÕES DE CRÉDITO",
  "17540501": "BIRD - PROGESTÃO",
  "17540502": "FUNDO CLIMA",
  "17550103": "ALIENAÇÃO DE BENS - ADMINISTRAÇÃO DIRETA",
  "17550700": "RECURSOS DE ALIENAÇÃO DE BENS/ATIVOS - ADMINISTRAÇÃO DIRETA",
  "17560070": "RECURSOS DE ALIENAÇÃO DE BENS/ATIVOS - ADMINISTRAÇÃO INDIRETA",
  "17560103": "RECURSOS DE ALIENAÇÃO DE BENS/ATIVOS - ADMINISTRAÇÃO INDIRETA",
  "17560700": "RECURSOS DE ALIENAÇÃO DE BENS/ATIVOS - ADMINISTRAÇÃO INDIRETA",
  "17570000": "RECURSOS DE DEPÓSITOS JUDICIAIS - LIDES DAS QUAIS O ENTE FAZ PARTE.",
  "17600700": "RECURSOS DE EMOLUMENTOS, TAXAS E CUSTAS",
  "18000000": "RECURSOS PREVIDENCIÁRIOS",
  "18001111": "BENEFÍCIOS PREVIDENCIÁRIOS - PODER EXECUTIVO ¿ FUNDO EM CAPITALIZAÇÃO (PLANO PREVIDENCIÁRIO)",
  "18010000": "RECURSOS DO RPPS - FUNDO EM REPARTIÇÃO (PLANO FINANCEIRO)",
  "18012111": "BENEFÍCIOS PREVIDENCIÁRIOS - PODER EXECUTIVO - FUNDO EM REPARTIÇÃO (PLANO FINANCEIRO)",
  "18020000": "RECURSOS VINCULADOS AO RPPS - TAXA DE ADMINISTRAÇÃO",
  "18020801": "RECURSOS VINCULADOS AO RPPS - TAXA DE ADMINISTRAÇÃO",
  "18032211": "BENEFÍCIOS PREVIDENCIÁRIOS - MILITARES SPSM",
  "18610000": "RECURSOS EXTRAORÇAMENTÁRIOS VINCULADOS A DEPÓSITOS JUDICIAIS",
  "18690000": "OUTROS RECURSOS EXTRAORÇAMENTÁRIOS",
  "18980000": "RECURSOS NÃO CLASSIFICADOS - A CLASSIFICAR",
  "25000100": "RECURSOS PRÓPRIOS DO TESOURO (SUPERÁVIT)",
  "25001001": "RECURSOS DESTINADOS À MANUT. E DES. DO ENSINO (25%) (SUPERÁVIT)",
  "25010100": "OUTRAS RESTITUIÇÕES AOS PODERES (Superávit)",
  "25010600": "RECURSOS ORDINÁRIOS DESVINCULADOS - DRE (SUPERÁVIT)",
  "25010700": "RECURSOS PRÓPRIOS ADM INDIRETA – NÃO VINCULADOS (SUPERÁVIT)",
  "25010701": "RECURSOS DO CIRA - NÃO VINCULADOS - ( SUPERÁVIT)",
  "25400300": "TRANSF. DO FUNDEB - IMPOSTOS E TRANSF. DE IMPOSTOS (SUPERÁVIT)",
  "25401070": "IDENT. DO PERC. APLIC. NA REMUN. PROF. DA EDUCAÇÃO BÁSICA (Superávit)",
  "25430300": "TRANSF. DO FUNDEB - COMPLEMENTAÇÃO DA UNIÃO - VAAR (SUPERÁVIT)",
  "25500102": "TRANSFERÊNCIAS DO SALÁRIO-EDUCAÇÃO (Superávit)",
  "25520200": "TRANSF. DE RECURSOS DO FNDE REFERENTES AO PNAE (SUPERÁVIT)",
  "25530200": "TRANSF. DE RECURSOS DO FNDE REFERENTES AO PNATE (SUPERÁVIT)",
  "25700200": "TRANSF. DO GOV. FEDERAL-CONVÊNIOS/REPASSES VINC. A EDUCAÇÃO (SUPERÁVIT)",
  "25703110": "EMENDAS PARLAMENTARES INDIVIDUAIS - (SUPERÁVIT)",
  "25703120": "EMENDAS PARLAMENTARES DE BANCADA - (SUPERÁVIT)",
  "25703130": "EMENDAS PARLAMENTARES DE COMISSÃO - EDUCAÇÃO (SUPERÁVIT);",
  "25730100": "ROYALTIES DO PETRÓLEO E GÁS NATURAL VINC. À EDUCAÇÃO (75%) - (SUPERÁVIT)",
  "26000400": "SUS - MANUTENÇÃO - (SUPERÁVIT)",
  "26003110": "EMENDAS PARLAMENTARES INDIVIDUAIS (SUPERÁVIT)",
  "26003120": "EMENDAS PARLAMENTARES DE BANCADA (SUPERÁVIT)",
  "26010400": "SUS - INVESTIMENTOS (SUPERÁVIT)",
  "26013110": "EMENDAS PARLAMENTARES INDIVIDUAIS (SUPERÁVIT)",
  "26013120": "EMENDAS PARLAMENTARES DE BANCADA (SUPERÁVIT)",
  "26020400": "REC. PARA AÇÕES E SERV DE SAÚDE - BLOCO MANUTENÇÃO COVID (SUPERÁVIT)",
  "26030400": "REC. DAS AÇÕES E SERV DE SAÚDE - BLOCO INVESTIMENTO COVID (SUPERÁVIT)",
  "26050400": "COMP. PAGAMENTO DO PISO SALARIAL DA ENFERMAGEM (Superávit)",
  "26310200": "TRANS. DO GOVERNO FEDERAL REF. A CONV. E INSTRUMENTOS CONGÊNERES VINCULADOS À SAÚDE (Superavit)",
  "26313110": "EMENDAS PARLAMENTARES INDIVIDUAIS - SAÚDE (SUPERÁVIT)",
  "26313120": "EMENDAS PARLAMENTARES DE BANCADA (SAÚDE) - SUPERÁVIT",
  "26313130": "EMENDAS PARLAMENTARES DE COMISSÃO - SAÚDE (SUPERÁVIT)",
  "26313140": "EMENDAS PARLAMENTARES DE RELATOR - SAÚDE (SUPERÁVIT)",
  "26350100": "ROYALTIES DO PETRÓLEO E GÁS NATURAL VINC À SAÚDE (25%) (SUPERÁVIT(",
  "26360200": "OUTRAS TRANSF DE CONV/INSTRUMENTOS CONGÊNERES VINC À SAÚDE (SUPERÁVIT)",
  "26600200": "TRANSF DE RECURSOS DO FUNDO NACIONAL DE ASSIST SOCIAL - FNAS (SUPERÁVIT)",
  "26603110": "EMENDAS PARLAMENTARES INDIVIDUAIS (SUPERÁVIT)",
  "26603120": "EMENDAS PARLAMENTARES DE BANCADA (FNS)- SUPERÁVIT",
  "26650200": "Transferências de Convênios e outros Repasses vinculados à Assistência Social (Superávit)",
  "26653110": "EMENDAS PARLAMENTARES INDIVIDUAIS ASSISTÊNCIA SOCIAL (SUPERÁVIT)",
  "26653120": "EMENDAS PARLAMENTARES DE BANCADA - ASSISTÊNCIA SOCIAL (SUPERÁVIT)",
  "26653130": "EMENDAS PARLAMENTARES DE COMISSÃO - ASSISTÊNCIA SOCIAL (SUPERÁVIT)",
  "27000200": "OUTRAS TRANSFERÊNCIAS DE CONVÊNIOS OU REPASSES DA UNIÃO (SUPERÁVIT)",
  "27000221": "TRANSFERÊNCIA DA UNIÃO - DEFESA CIVIL (SUPERÁVIT)",
  "27003110": "EMENDAS PARLAMENTARES INDIVIDUAIS (Superávit)",
  "27003120": "EMENDAS PARLAMENTARES DE BANCADA (Superávit)",
  "27003130": "EMENDAS PARLAMENTARES DE COMISSÃO (SUPERÁVIT)",
  "27003140": "EMENDAS PARLAMENTARES DE RELATOR (SUPERÁVIT)",
  "27010200": "OUTRAS TRANSFERÊNCIAS DE CONVÊNIOS OU INSTRUMENTOS CONGÊNERES DOS ESTADOS (SUPERÁVIT)",
  "27020200": "OUTRAS TRANSFERÊNCIAS DE CONVÊNIOS OU INSTRUMENTOS CONGÊNERES DOS MUNICÍPIOS (SUPERÁVIT)",
  "27030200": "CONTRIBUIÇÃO FINANCEIRA NÃO REEMBOLSÁVEL (SUPERÁVIT)",
  "27030202": "FUNDO AMAZÔNIA (SUPERÁVIT)",
  "27060201": "TRANSFERÊNCIA ESPECIAL DA UNIÃO (SUPERÁVIT)",
  "27063110": "TRANSFERÊNCIA ESPECIAL DA UNIÃO - SUPERÁVIT",
  "27070900": "RECURSOS DA LC 173/2020 (SUPERÁVIT)",
  "27120700": "TRANSFERÊNCIAS FUNDO A FUNDO DE RECURSOS DO FUNDO PENITENCIÁRIO - FUNPEN (SUPERÁVIT)",
  "27130700": "TRANSF FUNDO A FUNDO DE RECURSOS DO FSP (SUPERÁVIT)",
  "27150013": "TRANSF DEST AO SETOR CULTURAL-LC Nº195/2022-ART.5º AUDIOVIS (SUPERÁVIT)",
  "27160013": "TRANSF AO SETOR CULTURAL-LC Nº195/2022-ART.8º-DEMAIS SETORES (SUPERÁVIT)",
  "27180000": "AUX. FINANCEIRO-OUTORGA CRED ICMS ART.5 INC.V EC N.123/2022 (SUPERÁVIT)",
  "27190013": "TRANSF POLÍTICA NAC DE FOMENTO À CULTURA-LEI Nº 14.399/2022 (SUPERÁVIT)",
  "27520700": "RECURSOS PROVENIENTES DA ARRECADAÇÃO DE MULTAS DE TRÂNSITO (SUPERÁVIT)",
  "27530700": "RECURSOS PROVENIENTES DE TAXAS E CONTR E PREÇOS PÚBLICOS (SUPERÁVIT)",
  "27540500": "OPERAÇÕES DE CRÉDITO (SUPERÁVIT)",
  "27540501": "BIRD - PROGESTÃO (SUPERÁVIT)",
  "27550103": "ALIENAÇÃO DE BENS - ADMINISTRAÇÃO DIRETA (SUPERÁVIT)",
  "27560103": "RECURSOS DE ALIENAÇÃO DE BENS/ATIVOS - ADMINISTRAÇÃO INDIRETA (SUPERÁVIT)",
  "27600700": "RECURSOS DE EMOLUMENTOS, TAXAS E CUSTAS (SUPERÁVIT)",
  "28000000": "RECURSOS PREVIDENCIÁRIOS - SUPERÁVIT",
  "28020801": "RECURSOS VINC AO RPPS - TAXA DE ADMINISTRAÇÃO (SUPERÁVIT)",
};
